# Generated by Django 4.0.1 on 2024-05-08 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_model', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='product_details',
        ),
    ]
