# Generated by Django 4.0.1 on 2024-05-08 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='encoded_image',
            field=models.BinaryField(null=True),
        ),
    ]
