# Generated by Django 4.0.1 on 2024-05-08 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_encoded_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='encoded_image',
        ),
    ]
